version: 0.2

phases:
  pre_build:
    commands:
      - npm install
      - echo VITE_ENV=${VITE_ENV} >> .env
      - echo VITE_REACT_APP_USER_POOL_ID=${VITE_REACT_APP_USER_POOL_ID} >> .env
      - echo VITE_REACT_APP_CLIENT_ID=${VITE_REACT_APP_CLIENT_ID} >> .env
      - echo VITE_BASE_URL=${VITE_BASE_URL} >> .env
  build:
    commands:
      - npm run build
  post_build:
    commands:
      - aws s3 cp --recursive ./dist s3://www.constituent-connect.com/
      - aws cloudfront create-invalidation --distribution-id E3LDD6BFIH8W9O --path /\*
      - aws cloudfront create-invalidation --distribution-id E2899LLU33G2W0 --path /\*